name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests for reports
      run: pytest /home/nastia/PycharmProjects/5_assignment_fse/test_reports.py

    - name: Run unit tests for main
      run: pytest /home/nastia/PycharmProjects/5_assignment_fse/test_main.py

    - name: Run unit tests for users
      run: pytest /home/nastia/PycharmProjects/5_assignment_fse/test_users.py
